name: Test trunk
on:
  push:
    branches: trunk
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Wait until postgres has started.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      cms:
        image: joonashak/reclab-cms:latest
        ports:
          - 3001:3001
        env:
          NODE_ENV: development
          PORT: 3001
          DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
          JWT_SECRET: asd
        # Wait until cms has started.
        options: >-
          --health-cmd "curl -sS 127.0.0.1:3001/seeder/reset || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.8
      - run: npm ci
      - name: Run Linter
        run: npm run lint
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run serve
          wait-on: 'http://localhost:9000'
        env:
          NODE_ENV: test
          CMS_URL: http://127.0.0.1:3001
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
